VERSIONS_STATUS_DELETED = 0
VERSIONS_STATUS_UNPUBLISHED = 1
VERSIONS_STATUS_PUBLISHED = 2
VERSIONS_STATUS_CHOICES = (
    (VERSIONS_STATUS_DELETED, 'Deleted'),
    (VERSIONS_STATUS_UNPUBLISHED, 'Unpublished'),
    (VERSIONS_STATUS_PUBLISHED, 'Published'),
    )
