VERSIONS_STATUS_DELETED = 0
VERSIONS_STATUS_STAGED_EDITS = 1
VERSIONS_STATUS_PUBLISHED = 2
VERSIONS_STATUS_STAGED_DELETE = 3

VERSIONS_STATUS_CHOICES = (
    (VERSIONS_STATUS_PUBLISHED, 'Published'),
    (VERSIONS_STATUS_STAGED_EDITS, 'Staged Edits'),
    (VERSIONS_STATUS_STAGED_DELETE, 'Staged Delete'),
    (VERSIONS_STATUS_DELETED, 'Deleted'),
    )
